FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY postcss.config.js tailwind.config.js ./
COPY src ./src
COPY templates ./templates
COPY static ./static

CMD ["npm", "run", "build:css"]
