FROM python:3.11-slim

RUN pip install --no-cache-dir \
  dagster \
  dagster-webserver \
  dagster-graphql \
  selenium

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

WORKDIR /opt/dagster/app
