services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  dagu:
    build: ./dagu
    container_name: dagu
    restart: unless-stopped
    ports:
      - "3012:6806"
    volumes:
      - ./dagu/dags:/var/lib/dagu/dags
      - ./dagu/configs:/var/lib/dagu/configs
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/work/fisgon:/deps/fisgon
    environment:
      - DAGU_HOST=0.0.0.0
      - DAGU_PORT=6806
      - TZ=Europe/Madrid

  fisgon_api:
    build:
      context: /home/ubuntu/work/event_flask_app
    container_name: fisgon_api
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      PYTHONPATH: /app:/deps/fisgon
      DATA_STORAGE_PATH: /home/ubuntu/data_storage/
    ports:
      - "5002:5002"
    volumes:
      - /home/ubuntu/work/event_flask_app:/app
      - /home/ubuntu/work/fisgon:/deps/fisgon
      - /home/ubuntu/data_storage:/home/ubuntu/data_storage
    command: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5002/health"]
      interval: 30s
      timeout: 5s
      retries: 5
